### ISSUE TITLE
Detected as harmful app by Google Play Protect

### ISSUE THREAD

**Issue by valinet** [therealahrion/ViPER4Android-FX#14]
Hi

This morning, after just installing the 6.12.2018 update yesterday, a notification from Google Play Protect keeps popping up on my phone saying that 'Viper4Android FX may be harmful'. When I click on it, it simply says that 'This app tries to bypass Android's security protections' and offers the option to 'Keep app (unsafe)' or 'Disable' it.

Is there something to worry about or just a false positive? Could you implement something so that this detection does not happen anymore?

I am on the latest stable Magisk v17.1, and have installed the latest Material V4A as system app.

Thank you very much (as well, for a great module).

**Comment by fessmm** [comment]
Ignore that

**Comment by valinet** [comment]
Ok, any idea what may trigger the warning?

**Comment by Zackptg5** [comment]
This has been discussed on the xda thread multiple times. With V4A 2.5, a "developer mode" in settings was introduced which allows you to disable selinux. I don't know for sure what sets of play protect, but this is the most likely culprit (and for good reason). Just ignore it, V4A is a clean app
