### ISSUE TITLE
Driver Installation issue

### ISSUE THREAD

**Issue by vaasishtha** [therealahrion/ViPER4Android-FX#17]
The app keeps asking for the insstallation of the driver which doesn't happen.
This issue is after Apr 02 update. It used to work perfectly fine before that. Now i've tried it over and over, but doesn't seem to do anything.

**Comment by Zackptg5** [comment]
Make a proper bug report in the xda thread. There's a troubleshooting guide in the OP - I'm also assuming you tried some of the options like the lib and open/close workarounds
