### ISSUE TITLE
Issue During video calls

### ISSUE THREAD

**Issue by ozomax1997** [therealahrion/ViPER4Android-FX#18]
I Have a issue when trying to make any video calls when Viper4Android is installed where sound is choppy and sort of robotic. It doesn't matter what provider I use weather it be FB, WhatsApp Skype etc. I have attached as much information as I can below>

Install Method: Magisk
          Installation options:
          1: New (2.5.0.5)
          2: Material UI 
          3: System App
          4: No Lib Workaround
          5: No Auto FC Workaround

Driver Status:
         Driver Version: 2.5.0.4
         Neon Enabled: Yes
         Status: Normal
         Audio Format: Supported
         Processing: No
         Sampling Rate: 48000

Device Information
        Manufacturer: Xiaomi
        Model: Mi 8 (Dipper)
        Android Version: 9.0
        Rom: Pixel Experience (Build Date 2019/04/06)

**Comment by Zackptg5** [comment]
Github issues is a place for a bug in the installer itself, not for v4a app problems (I'm not the dev of the app itself) so this would be best on the xda thread. I'm sure this has been brought up numerous times too so definitely search the thread
