### ISSUE TITLE
Conflict with EdXposed Module And Quickstep

### ISSUE THREAD

**Issue by rushiranpise** [therealahrion/ViPER4Android-FX#19]
If I install Edxposed module + Latest viper4fx, edxposed module shows framework is installed,but the modules says it isn't enable. 
But if i uninstall viper4fx module it works fine!
And quicksteps also have similar error 
Even topjohnwu says it related with modules itself

https://github.com/topjohnwu/Magisk/issues/1437#issuecomment-491463545

**Comment by rushiranpise** [comment]
Device moto g2 , Android pie , rr 7.0.2 . Magisk 19.1, beta

**Comment by Zackptg5** [comment]
It's an edxposed issue. V4a does nothing that could interfere with it or any other module for that matter. The fact that when edxposed is installed with other modules, the same thing happens is proof of that
