### ISSUE TITLE
Nexus 6P driver installed and 'on' but processing always 'no'

### ISSUE THREAD

**Issue by Zerqz** [therealahrion/ViPER4Android-FX#3]
I've tried switching between normal and compatible mode, used a wide array of apps to test (Firefox, Spotify, VLC, Google Photos-played a video-, and even games), and it always says "processing: no" in the driver status window, but everything else is yes/on, and there is no noticeable difference with the audio in normal or compatible mode. I turned reverb waayyy up so it should have been pretty obvious if it was working or not.

I'm on a Nexus 6P running Resurrection Remix rom, android 7.1.1.

**Comment by Zackptg5** [comment]
You need to removal deep_buffer. Flash ahrion's deep_buffer removal module/zip

**Comment by Zerqz** [comment]
Works perfectly now!! Thanks.

-Z

-------- Original Message --------

**Comment by Zackptg5** [comment]
If it's resolved, close the issue please :)
