### ISSUE TITLE
Magisk V13 driver abnormal

### ISSUE THREAD

**Issue by ghost** [therealahrion/ViPER4Android-FX#4]
When using magisk 13.1 or higher the driver status is always abnormal and ViperFX does not work.

It can be fixed with the following /magisk/v4a/post-fs-data.sh:

#!/system/bin/sh

sepolicy-inject --live "allow mediaserver mediaserver_tmpfs file { read write execute }" \
"allow audioserver audioserver_tmpfs file { read write execute }"

**Comment by Zackptg5** [comment]
This is a known issue and will be fixed in the next release :)

**Comment by Zackptg5** [comment]
Fixed :)
