### ISSUE TITLE
Support Pixel 2 slot detection

### ISSUE THREAD

**Issue by scottismyname** [therealahrion/ViPER4Android-FX#6]
I believe slot detection is broken for the Pixel 2 XL.  Please see the newest slot detection code commited to magisk for details:

https://github.com/topjohnwu/Magisk/blob/8c02d120a247f637d14a7a900cf52c82f9ab482c/scripts/util_functions.sh#L43

The problem for the Pixel 2 XL is that it uses a different build.prop setting.

**Comment by Zackptg5** [comment]
Added it in. Thanks for the heads up! Next aml version will be pixel 2 compatible :)

**Comment by scottismyname** [comment]
Does this mean SELinux support for Oreo will be fixed? Even with slot detection working, it only works in Permissive mode

**Comment by Zackptg5** [comment]
I don't have a device with oreo yet that I can test so I couldn't tell you. The slot detection will allow the module to install but selinux is a separate matter entirely.
Oreo brings it's own set of problems. For example, none of the dolby ports work on oreo, even with selinux set to permissive. Once one of my test devices gets an oreo rom, I'll start looking into it
