### ISSUE TITLE
V4A app doesn't install, disables magisk modules

### ISSUE THREAD

**Issue by ghost** [therealahrion/ViPER4Android-FX#8]
Android 7 | Magisk 14.3 | SM-A520F
When I download this through Magisk Manager and reboot the V4A app doesn't install. In addition, it actually disables magisk modules so youtube vanced ceases to work.

**Comment by Zackptg5** [comment]
AML and this mod has been updated to new magisk template so it's only compatibile with magisk 15+
Try v2.7 with magisk 15
